# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8401dba5e37a862351d8eb2c49b01276"
application_url = "https://gained-trio-intense-docs.trycloudflare.com"
embedded = true
name = "Poppy"
handle = "poppy-4"

[build]
include_config_on_deploy = true
dev_store_url = "developer52.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobjects,write_files,write_metaobject_definitions,write_metaobjects,write_products,write_themes"

[auth]
redirect_urls = [
  "https://gained-trio-intense-docs.trycloudflare.com/auth/callback",
  "https://gained-trio-intense-docs.trycloudflare.com/auth/shopify/callback",
  "https://gained-trio-intense-docs.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
