# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "80fbf6352378a2a38a09685dd9b33fb4"
application_url = "https://breeds-monitoring-r-never.trycloudflare.com"
embedded = true
name = "Popup & Disclaimer"
handle = "popup-and-disclaimer"

[build]
dev_store_url = "konain-raza.myshopify.com"
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobjects,write_files,write_metaobject_definitions,write_metaobjects,write_products,write_themes"

[auth]
redirect_urls = [
  "https://breeds-monitoring-r-never.trycloudflare.com/auth/callback",
  "https://breeds-monitoring-r-never.trycloudflare.com/auth/shopify/callback",
  "https://breeds-monitoring-r-never.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
