# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "80fbf6352378a2a38a09685dd9b33fb4"
application_url = "https://disturbed-paperback-sites-glad.trycloudflare.com"
embedded = true
name = "Popup & Disclaimer"
handle = "popup-and-disclaimer"

[webhooks]
api_version = "2025-04"
  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobjects,write_files,write_metaobject_definitions,write_metaobjects,write_products,write_themes"

[auth]
redirect_urls = [
  "https://disturbed-paperback-sites-glad.trycloudflare.com/auth/callback",
  "https://disturbed-paperback-sites-glad.trycloudflare.com/auth/shopify/callback",
  "https://disturbed-paperback-sites-glad.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "objectstesting.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
